//
// This program source code file is part of KiCad, a free EDA CAD application.
//
// Copyright (C) 2024 Jon Evans <jon@craftyjon.com>
// Copyright (C) 2024 KiCad Developers, see AUTHORS.txt for contributors.
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: board/board.proto

package board

import (
	types "github.com/kicad/proto/common/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoardStackupLayerType int32

const (
	BoardStackupLayerType_BSLT_UNKNOWN     BoardStackupLayerType = 0
	BoardStackupLayerType_BSLT_COPPER      BoardStackupLayerType = 1
	BoardStackupLayerType_BSLT_DIELECTRIC  BoardStackupLayerType = 2
	BoardStackupLayerType_BSLT_SILKSCREEN  BoardStackupLayerType = 3
	BoardStackupLayerType_BSLT_SOLDERMASK  BoardStackupLayerType = 4
	BoardStackupLayerType_BSLT_SOLDERPASTE BoardStackupLayerType = 5
	BoardStackupLayerType_BSLT_UNDEFINED   BoardStackupLayerType = 7
)

// Enum value maps for BoardStackupLayerType.
var (
	BoardStackupLayerType_name = map[int32]string{
		0: "BSLT_UNKNOWN",
		1: "BSLT_COPPER",
		2: "BSLT_DIELECTRIC",
		3: "BSLT_SILKSCREEN",
		4: "BSLT_SOLDERMASK",
		5: "BSLT_SOLDERPASTE",
		7: "BSLT_UNDEFINED",
	}
	BoardStackupLayerType_value = map[string]int32{
		"BSLT_UNKNOWN":     0,
		"BSLT_COPPER":      1,
		"BSLT_DIELECTRIC":  2,
		"BSLT_SILKSCREEN":  3,
		"BSLT_SOLDERMASK":  4,
		"BSLT_SOLDERPASTE": 5,
		"BSLT_UNDEFINED":   7,
	}
)

func (x BoardStackupLayerType) Enum() *BoardStackupLayerType {
	p := new(BoardStackupLayerType)
	*p = x
	return p
}

func (x BoardStackupLayerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoardStackupLayerType) Descriptor() protoreflect.EnumDescriptor {
	return file_board_board_proto_enumTypes[0].Descriptor()
}

func (BoardStackupLayerType) Type() protoreflect.EnumType {
	return &file_board_board_proto_enumTypes[0]
}

func (x BoardStackupLayerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoardStackupLayerType.Descriptor instead.
func (BoardStackupLayerType) EnumDescriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{0}
}

// LAYER_CLASS_* in BOARD_DESIGN_SETTINGS -- needs to become an enum class
type BoardLayerClass int32

const (
	BoardLayerClass_BLC_UNKNOWN     BoardLayerClass = 0
	BoardLayerClass_BLC_SILKSCREEN  BoardLayerClass = 1
	BoardLayerClass_BLC_COPPER      BoardLayerClass = 2
	BoardLayerClass_BLC_EDGES       BoardLayerClass = 3
	BoardLayerClass_BLC_COURTYARD   BoardLayerClass = 4
	BoardLayerClass_BLC_FABRICATION BoardLayerClass = 5
	BoardLayerClass_BLC_OTHER       BoardLayerClass = 6
)

// Enum value maps for BoardLayerClass.
var (
	BoardLayerClass_name = map[int32]string{
		0: "BLC_UNKNOWN",
		1: "BLC_SILKSCREEN",
		2: "BLC_COPPER",
		3: "BLC_EDGES",
		4: "BLC_COURTYARD",
		5: "BLC_FABRICATION",
		6: "BLC_OTHER",
	}
	BoardLayerClass_value = map[string]int32{
		"BLC_UNKNOWN":     0,
		"BLC_SILKSCREEN":  1,
		"BLC_COPPER":      2,
		"BLC_EDGES":       3,
		"BLC_COURTYARD":   4,
		"BLC_FABRICATION": 5,
		"BLC_OTHER":       6,
	}
)

func (x BoardLayerClass) Enum() *BoardLayerClass {
	p := new(BoardLayerClass)
	*p = x
	return p
}

func (x BoardLayerClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoardLayerClass) Descriptor() protoreflect.EnumDescriptor {
	return file_board_board_proto_enumTypes[1].Descriptor()
}

func (BoardLayerClass) Type() protoreflect.EnumType {
	return &file_board_board_proto_enumTypes[1]
}

func (x BoardLayerClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoardLayerClass.Descriptor instead.
func (BoardLayerClass) EnumDescriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{1}
}

type BoardFinish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardFinish) Reset() {
	*x = BoardFinish{}
	mi := &file_board_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardFinish) ProtoMessage() {}

func (x *BoardFinish) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardFinish.ProtoReflect.Descriptor instead.
func (*BoardFinish) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{0}
}

func (x *BoardFinish) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type BoardImpedanceControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsControlled  bool                   `protobuf:"varint,1,opt,name=is_controlled,json=isControlled,proto3" json:"is_controlled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardImpedanceControl) Reset() {
	*x = BoardImpedanceControl{}
	mi := &file_board_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardImpedanceControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardImpedanceControl) ProtoMessage() {}

func (x *BoardImpedanceControl) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardImpedanceControl.ProtoReflect.Descriptor instead.
func (*BoardImpedanceControl) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{1}
}

func (x *BoardImpedanceControl) GetIsControlled() bool {
	if x != nil {
		return x.IsControlled
	}
	return false
}

type BoardEdgeConnector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardEdgeConnector) Reset() {
	*x = BoardEdgeConnector{}
	mi := &file_board_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardEdgeConnector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardEdgeConnector) ProtoMessage() {}

func (x *BoardEdgeConnector) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardEdgeConnector.ProtoReflect.Descriptor instead.
func (*BoardEdgeConnector) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{2}
}

type Castellation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HasCastellatedPads bool                   `protobuf:"varint,1,opt,name=has_castellated_pads,json=hasCastellatedPads,proto3" json:"has_castellated_pads,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Castellation) Reset() {
	*x = Castellation{}
	mi := &file_board_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Castellation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Castellation) ProtoMessage() {}

func (x *Castellation) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Castellation.ProtoReflect.Descriptor instead.
func (*Castellation) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{3}
}

func (x *Castellation) GetHasCastellatedPads() bool {
	if x != nil {
		return x.HasCastellatedPads
	}
	return false
}

type EdgePlating struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasEdgePlating bool                   `protobuf:"varint,1,opt,name=has_edge_plating,json=hasEdgePlating,proto3" json:"has_edge_plating,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EdgePlating) Reset() {
	*x = EdgePlating{}
	mi := &file_board_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgePlating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgePlating) ProtoMessage() {}

func (x *EdgePlating) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgePlating.ProtoReflect.Descriptor instead.
func (*EdgePlating) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{4}
}

func (x *EdgePlating) GetHasEdgePlating() bool {
	if x != nil {
		return x.HasEdgePlating
	}
	return false
}

type BoardEdgeSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *BoardEdgeConnector    `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	Castellation  *Castellation          `protobuf:"bytes,2,opt,name=castellation,proto3" json:"castellation,omitempty"`
	Plating       *EdgePlating           `protobuf:"bytes,3,opt,name=plating,proto3" json:"plating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardEdgeSettings) Reset() {
	*x = BoardEdgeSettings{}
	mi := &file_board_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardEdgeSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardEdgeSettings) ProtoMessage() {}

func (x *BoardEdgeSettings) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardEdgeSettings.ProtoReflect.Descriptor instead.
func (*BoardEdgeSettings) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{5}
}

func (x *BoardEdgeSettings) GetConnector() *BoardEdgeConnector {
	if x != nil {
		return x.Connector
	}
	return nil
}

func (x *BoardEdgeSettings) GetCastellation() *Castellation {
	if x != nil {
		return x.Castellation
	}
	return nil
}

func (x *BoardEdgeSettings) GetPlating() *EdgePlating {
	if x != nil {
		return x.Plating
	}
	return nil
}

type BoardStackupCopperLayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardStackupCopperLayer) Reset() {
	*x = BoardStackupCopperLayer{}
	mi := &file_board_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardStackupCopperLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardStackupCopperLayer) ProtoMessage() {}

func (x *BoardStackupCopperLayer) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardStackupCopperLayer.ProtoReflect.Descriptor instead.
func (*BoardStackupCopperLayer) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{6}
}

type BoardStackupDielectricProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpsilonR      float64                `protobuf:"fixed64,1,opt,name=epsilon_r,json=epsilonR,proto3" json:"epsilon_r,omitempty"`
	LossTangent   float64                `protobuf:"fixed64,2,opt,name=loss_tangent,json=lossTangent,proto3" json:"loss_tangent,omitempty"`
	MaterialName  string                 `protobuf:"bytes,3,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"`
	Thickness     *types.Distance        `protobuf:"bytes,4,opt,name=thickness,proto3" json:"thickness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardStackupDielectricProperties) Reset() {
	*x = BoardStackupDielectricProperties{}
	mi := &file_board_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardStackupDielectricProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardStackupDielectricProperties) ProtoMessage() {}

func (x *BoardStackupDielectricProperties) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardStackupDielectricProperties.ProtoReflect.Descriptor instead.
func (*BoardStackupDielectricProperties) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{7}
}

func (x *BoardStackupDielectricProperties) GetEpsilonR() float64 {
	if x != nil {
		return x.EpsilonR
	}
	return 0
}

func (x *BoardStackupDielectricProperties) GetLossTangent() float64 {
	if x != nil {
		return x.LossTangent
	}
	return 0
}

func (x *BoardStackupDielectricProperties) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

func (x *BoardStackupDielectricProperties) GetThickness() *types.Distance {
	if x != nil {
		return x.Thickness
	}
	return nil
}

type BoardStackupDielectricLayer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A single dielectric slot (between copper layers) can be made up of multiple physical layers
	Layer         []*BoardStackupDielectricProperties `protobuf:"bytes,1,rep,name=layer,proto3" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardStackupDielectricLayer) Reset() {
	*x = BoardStackupDielectricLayer{}
	mi := &file_board_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardStackupDielectricLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardStackupDielectricLayer) ProtoMessage() {}

func (x *BoardStackupDielectricLayer) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardStackupDielectricLayer.ProtoReflect.Descriptor instead.
func (*BoardStackupDielectricLayer) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{8}
}

func (x *BoardStackupDielectricLayer) GetLayer() []*BoardStackupDielectricProperties {
	if x != nil {
		return x.Layer
	}
	return nil
}

type BoardStackupLayer struct {
	state        protoimpl.MessageState       `protogen:"open.v1"`
	Thickness    *types.Distance              `protobuf:"bytes,1,opt,name=thickness,proto3" json:"thickness,omitempty"`
	Layer        BoardLayer                   `protobuf:"varint,2,opt,name=layer,proto3,enum=kiapi.board.types.BoardLayer" json:"layer,omitempty"`
	Enabled      bool                         `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Type         BoardStackupLayerType        `protobuf:"varint,4,opt,name=type,proto3,enum=kiapi.board.BoardStackupLayerType" json:"type,omitempty"`
	Dielectric   *BoardStackupDielectricLayer `protobuf:"bytes,5,opt,name=dielectric,proto3" json:"dielectric,omitempty"`
	Color        *types.Color                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	MaterialName string                       `protobuf:"bytes,7,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"`
	// The name of the layer shown in the KiCad GUI, which may be a default value like "F.Cu" or may
	// have been customized by the user.  This field does not apply to dielectric layers.
	UserName      string `protobuf:"bytes,8,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardStackupLayer) Reset() {
	*x = BoardStackupLayer{}
	mi := &file_board_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardStackupLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardStackupLayer) ProtoMessage() {}

func (x *BoardStackupLayer) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardStackupLayer.ProtoReflect.Descriptor instead.
func (*BoardStackupLayer) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{9}
}

func (x *BoardStackupLayer) GetThickness() *types.Distance {
	if x != nil {
		return x.Thickness
	}
	return nil
}

func (x *BoardStackupLayer) GetLayer() BoardLayer {
	if x != nil {
		return x.Layer
	}
	return BoardLayer_BL_UNKNOWN
}

func (x *BoardStackupLayer) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BoardStackupLayer) GetType() BoardStackupLayerType {
	if x != nil {
		return x.Type
	}
	return BoardStackupLayerType_BSLT_UNKNOWN
}

func (x *BoardStackupLayer) GetDielectric() *BoardStackupDielectricLayer {
	if x != nil {
		return x.Dielectric
	}
	return nil
}

func (x *BoardStackupLayer) GetColor() *types.Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *BoardStackupLayer) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

func (x *BoardStackupLayer) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type BoardStackup struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Finish    *BoardFinish           `protobuf:"bytes,1,opt,name=finish,proto3" json:"finish,omitempty"`
	Impedance *BoardImpedanceControl `protobuf:"bytes,2,opt,name=impedance,proto3" json:"impedance,omitempty"`
	// NOTE: m_HasThicknessConstrains appears to be unused
	Edge          *BoardEdgeSettings   `protobuf:"bytes,3,opt,name=edge,proto3" json:"edge,omitempty"`
	Layers        []*BoardStackupLayer `protobuf:"bytes,4,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardStackup) Reset() {
	*x = BoardStackup{}
	mi := &file_board_board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardStackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardStackup) ProtoMessage() {}

func (x *BoardStackup) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardStackup.ProtoReflect.Descriptor instead.
func (*BoardStackup) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{10}
}

func (x *BoardStackup) GetFinish() *BoardFinish {
	if x != nil {
		return x.Finish
	}
	return nil
}

func (x *BoardStackup) GetImpedance() *BoardImpedanceControl {
	if x != nil {
		return x.Impedance
	}
	return nil
}

func (x *BoardStackup) GetEdge() *BoardEdgeSettings {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *BoardStackup) GetLayers() []*BoardStackupLayer {
	if x != nil {
		return x.Layers
	}
	return nil
}

type BoardLayerGraphicsDefaults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         BoardLayerClass        `protobuf:"varint,1,opt,name=layer,proto3,enum=kiapi.board.BoardLayerClass" json:"layer,omitempty"`
	Text          *types.TextAttributes  `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	LineThickness *types.Distance        `protobuf:"bytes,3,opt,name=line_thickness,json=lineThickness,proto3" json:"line_thickness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardLayerGraphicsDefaults) Reset() {
	*x = BoardLayerGraphicsDefaults{}
	mi := &file_board_board_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardLayerGraphicsDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardLayerGraphicsDefaults) ProtoMessage() {}

func (x *BoardLayerGraphicsDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardLayerGraphicsDefaults.ProtoReflect.Descriptor instead.
func (*BoardLayerGraphicsDefaults) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{11}
}

func (x *BoardLayerGraphicsDefaults) GetLayer() BoardLayerClass {
	if x != nil {
		return x.Layer
	}
	return BoardLayerClass_BLC_UNKNOWN
}

func (x *BoardLayerGraphicsDefaults) GetText() *types.TextAttributes {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *BoardLayerGraphicsDefaults) GetLineThickness() *types.Distance {
	if x != nil {
		return x.LineThickness
	}
	return nil
}

type GraphicsDefaults struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Layers        []*BoardLayerGraphicsDefaults `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphicsDefaults) Reset() {
	*x = GraphicsDefaults{}
	mi := &file_board_board_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphicsDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphicsDefaults) ProtoMessage() {}

func (x *GraphicsDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphicsDefaults.ProtoReflect.Descriptor instead.
func (*GraphicsDefaults) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{12}
}

func (x *GraphicsDefaults) GetLayers() []*BoardLayerGraphicsDefaults {
	if x != nil {
		return x.Layers
	}
	return nil
}

// Anything that isn't stackup or design rules
type BoardSettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GraphicsDefaults *GraphicsDefaults      `protobuf:"bytes,1,opt,name=graphics_defaults,json=graphicsDefaults,proto3" json:"graphics_defaults,omitempty"` // Dimension default settings
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BoardSettings) Reset() {
	*x = BoardSettings{}
	mi := &file_board_board_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardSettings) ProtoMessage() {}

func (x *BoardSettings) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardSettings.ProtoReflect.Descriptor instead.
func (*BoardSettings) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{13}
}

func (x *BoardSettings) GetGraphicsDefaults() *GraphicsDefaults {
	if x != nil {
		return x.GraphicsDefaults
	}
	return nil
}

type BoardDesignRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardDesignRules) Reset() {
	*x = BoardDesignRules{}
	mi := &file_board_board_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardDesignRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardDesignRules) ProtoMessage() {}

func (x *BoardDesignRules) ProtoReflect() protoreflect.Message {
	mi := &file_board_board_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardDesignRules.ProtoReflect.Descriptor instead.
func (*BoardDesignRules) Descriptor() ([]byte, []int) {
	return file_board_board_proto_rawDescGZIP(), []int{14}
}

var File_board_board_proto protoreflect.FileDescriptor

const file_board_board_proto_rawDesc = "" +
	"\n" +
	"\x11board/board.proto\x12\vkiapi.board\x1a\x1dcommon/types/base_types.proto\x1a\x17board/board_types.proto\"*\n" +
	"\vBoardFinish\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\"<\n" +
	"\x15BoardImpedanceControl\x12#\n" +
	"\ris_controlled\x18\x01 \x01(\bR\fisControlled\"\x14\n" +
	"\x12BoardEdgeConnector\"@\n" +
	"\fCastellation\x120\n" +
	"\x14has_castellated_pads\x18\x01 \x01(\bR\x12hasCastellatedPads\"7\n" +
	"\vEdgePlating\x12(\n" +
	"\x10has_edge_plating\x18\x01 \x01(\bR\x0ehasEdgePlating\"\xc5\x01\n" +
	"\x11BoardEdgeSettings\x12=\n" +
	"\tconnector\x18\x01 \x01(\v2\x1f.kiapi.board.BoardEdgeConnectorR\tconnector\x12=\n" +
	"\fcastellation\x18\x02 \x01(\v2\x19.kiapi.board.CastellationR\fcastellation\x122\n" +
	"\aplating\x18\x03 \x01(\v2\x18.kiapi.board.EdgePlatingR\aplating\"\x19\n" +
	"\x17BoardStackupCopperLayer\"\xc3\x01\n" +
	" BoardStackupDielectricProperties\x12\x1b\n" +
	"\tepsilon_r\x18\x01 \x01(\x01R\bepsilonR\x12!\n" +
	"\floss_tangent\x18\x02 \x01(\x01R\vlossTangent\x12#\n" +
	"\rmaterial_name\x18\x03 \x01(\tR\fmaterialName\x12:\n" +
	"\tthickness\x18\x04 \x01(\v2\x1c.kiapi.common.types.DistanceR\tthickness\"b\n" +
	"\x1bBoardStackupDielectricLayer\x12C\n" +
	"\x05layer\x18\x01 \x03(\v2-.kiapi.board.BoardStackupDielectricPropertiesR\x05layer\"\x93\x03\n" +
	"\x11BoardStackupLayer\x12:\n" +
	"\tthickness\x18\x01 \x01(\v2\x1c.kiapi.common.types.DistanceR\tthickness\x123\n" +
	"\x05layer\x18\x02 \x01(\x0e2\x1d.kiapi.board.types.BoardLayerR\x05layer\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x126\n" +
	"\x04type\x18\x04 \x01(\x0e2\".kiapi.board.BoardStackupLayerTypeR\x04type\x12H\n" +
	"\n" +
	"dielectric\x18\x05 \x01(\v2(.kiapi.board.BoardStackupDielectricLayerR\n" +
	"dielectric\x12/\n" +
	"\x05color\x18\x06 \x01(\v2\x19.kiapi.common.types.ColorR\x05color\x12#\n" +
	"\rmaterial_name\x18\a \x01(\tR\fmaterialName\x12\x1b\n" +
	"\tuser_name\x18\b \x01(\tR\buserName\"\xee\x01\n" +
	"\fBoardStackup\x120\n" +
	"\x06finish\x18\x01 \x01(\v2\x18.kiapi.board.BoardFinishR\x06finish\x12@\n" +
	"\timpedance\x18\x02 \x01(\v2\".kiapi.board.BoardImpedanceControlR\timpedance\x122\n" +
	"\x04edge\x18\x03 \x01(\v2\x1e.kiapi.board.BoardEdgeSettingsR\x04edge\x126\n" +
	"\x06layers\x18\x04 \x03(\v2\x1e.kiapi.board.BoardStackupLayerR\x06layers\"\xcd\x01\n" +
	"\x1aBoardLayerGraphicsDefaults\x122\n" +
	"\x05layer\x18\x01 \x01(\x0e2\x1c.kiapi.board.BoardLayerClassR\x05layer\x126\n" +
	"\x04text\x18\x02 \x01(\v2\".kiapi.common.types.TextAttributesR\x04text\x12C\n" +
	"\x0eline_thickness\x18\x03 \x01(\v2\x1c.kiapi.common.types.DistanceR\rlineThickness\"S\n" +
	"\x10GraphicsDefaults\x12?\n" +
	"\x06layers\x18\x01 \x03(\v2'.kiapi.board.BoardLayerGraphicsDefaultsR\x06layers\"[\n" +
	"\rBoardSettings\x12J\n" +
	"\x11graphics_defaults\x18\x01 \x01(\v2\x1d.kiapi.board.GraphicsDefaultsR\x10graphicsDefaults\"\x12\n" +
	"\x10BoardDesignRules*\xa3\x01\n" +
	"\x15BoardStackupLayerType\x12\x10\n" +
	"\fBSLT_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vBSLT_COPPER\x10\x01\x12\x13\n" +
	"\x0fBSLT_DIELECTRIC\x10\x02\x12\x13\n" +
	"\x0fBSLT_SILKSCREEN\x10\x03\x12\x13\n" +
	"\x0fBSLT_SOLDERMASK\x10\x04\x12\x14\n" +
	"\x10BSLT_SOLDERPASTE\x10\x05\x12\x12\n" +
	"\x0eBSLT_UNDEFINED\x10\a*\x8c\x01\n" +
	"\x0fBoardLayerClass\x12\x0f\n" +
	"\vBLC_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eBLC_SILKSCREEN\x10\x01\x12\x0e\n" +
	"\n" +
	"BLC_COPPER\x10\x02\x12\r\n" +
	"\tBLC_EDGES\x10\x03\x12\x11\n" +
	"\rBLC_COURTYARD\x10\x04\x12\x13\n" +
	"\x0fBLC_FABRICATION\x10\x05\x12\r\n" +
	"\tBLC_OTHER\x10\x06B\x1eZ\x1cgithub.com/kicad/proto/boardb\x06proto3"

var (
	file_board_board_proto_rawDescOnce sync.Once
	file_board_board_proto_rawDescData []byte
)

func file_board_board_proto_rawDescGZIP() []byte {
	file_board_board_proto_rawDescOnce.Do(func() {
		file_board_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_board_board_proto_rawDesc), len(file_board_board_proto_rawDesc)))
	})
	return file_board_board_proto_rawDescData
}

var file_board_board_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_board_board_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_board_board_proto_goTypes = []any{
	(BoardStackupLayerType)(0),               // 0: kiapi.board.BoardStackupLayerType
	(BoardLayerClass)(0),                     // 1: kiapi.board.BoardLayerClass
	(*BoardFinish)(nil),                      // 2: kiapi.board.BoardFinish
	(*BoardImpedanceControl)(nil),            // 3: kiapi.board.BoardImpedanceControl
	(*BoardEdgeConnector)(nil),               // 4: kiapi.board.BoardEdgeConnector
	(*Castellation)(nil),                     // 5: kiapi.board.Castellation
	(*EdgePlating)(nil),                      // 6: kiapi.board.EdgePlating
	(*BoardEdgeSettings)(nil),                // 7: kiapi.board.BoardEdgeSettings
	(*BoardStackupCopperLayer)(nil),          // 8: kiapi.board.BoardStackupCopperLayer
	(*BoardStackupDielectricProperties)(nil), // 9: kiapi.board.BoardStackupDielectricProperties
	(*BoardStackupDielectricLayer)(nil),      // 10: kiapi.board.BoardStackupDielectricLayer
	(*BoardStackupLayer)(nil),                // 11: kiapi.board.BoardStackupLayer
	(*BoardStackup)(nil),                     // 12: kiapi.board.BoardStackup
	(*BoardLayerGraphicsDefaults)(nil),       // 13: kiapi.board.BoardLayerGraphicsDefaults
	(*GraphicsDefaults)(nil),                 // 14: kiapi.board.GraphicsDefaults
	(*BoardSettings)(nil),                    // 15: kiapi.board.BoardSettings
	(*BoardDesignRules)(nil),                 // 16: kiapi.board.BoardDesignRules
	(*types.Distance)(nil),                   // 17: kiapi.common.types.Distance
	(BoardLayer)(0),                          // 18: kiapi.board.types.BoardLayer
	(*types.Color)(nil),                      // 19: kiapi.common.types.Color
	(*types.TextAttributes)(nil),             // 20: kiapi.common.types.TextAttributes
}
var file_board_board_proto_depIdxs = []int32{
	4,  // 0: kiapi.board.BoardEdgeSettings.connector:type_name -> kiapi.board.BoardEdgeConnector
	5,  // 1: kiapi.board.BoardEdgeSettings.castellation:type_name -> kiapi.board.Castellation
	6,  // 2: kiapi.board.BoardEdgeSettings.plating:type_name -> kiapi.board.EdgePlating
	17, // 3: kiapi.board.BoardStackupDielectricProperties.thickness:type_name -> kiapi.common.types.Distance
	9,  // 4: kiapi.board.BoardStackupDielectricLayer.layer:type_name -> kiapi.board.BoardStackupDielectricProperties
	17, // 5: kiapi.board.BoardStackupLayer.thickness:type_name -> kiapi.common.types.Distance
	18, // 6: kiapi.board.BoardStackupLayer.layer:type_name -> kiapi.board.types.BoardLayer
	0,  // 7: kiapi.board.BoardStackupLayer.type:type_name -> kiapi.board.BoardStackupLayerType
	10, // 8: kiapi.board.BoardStackupLayer.dielectric:type_name -> kiapi.board.BoardStackupDielectricLayer
	19, // 9: kiapi.board.BoardStackupLayer.color:type_name -> kiapi.common.types.Color
	2,  // 10: kiapi.board.BoardStackup.finish:type_name -> kiapi.board.BoardFinish
	3,  // 11: kiapi.board.BoardStackup.impedance:type_name -> kiapi.board.BoardImpedanceControl
	7,  // 12: kiapi.board.BoardStackup.edge:type_name -> kiapi.board.BoardEdgeSettings
	11, // 13: kiapi.board.BoardStackup.layers:type_name -> kiapi.board.BoardStackupLayer
	1,  // 14: kiapi.board.BoardLayerGraphicsDefaults.layer:type_name -> kiapi.board.BoardLayerClass
	20, // 15: kiapi.board.BoardLayerGraphicsDefaults.text:type_name -> kiapi.common.types.TextAttributes
	17, // 16: kiapi.board.BoardLayerGraphicsDefaults.line_thickness:type_name -> kiapi.common.types.Distance
	13, // 17: kiapi.board.GraphicsDefaults.layers:type_name -> kiapi.board.BoardLayerGraphicsDefaults
	14, // 18: kiapi.board.BoardSettings.graphics_defaults:type_name -> kiapi.board.GraphicsDefaults
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_board_board_proto_init() }
func file_board_board_proto_init() {
	if File_board_board_proto != nil {
		return
	}
	file_board_board_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_board_board_proto_rawDesc), len(file_board_board_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_board_board_proto_goTypes,
		DependencyIndexes: file_board_board_proto_depIdxs,
		EnumInfos:         file_board_board_proto_enumTypes,
		MessageInfos:      file_board_board_proto_msgTypes,
	}.Build()
	File_board_board_proto = out.File
	file_board_board_proto_goTypes = nil
	file_board_board_proto_depIdxs = nil
}
